# Generated by Django 5.1.5 on 2025-02-03 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_alter_worker_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="teams",
            field=models.ManyToManyField(
                blank=True, through="task_manager.ProjectTeam", to="task_manager.team"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                through="task_manager.TaskWorker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="teams",
            field=models.ManyToManyField(
                blank=True, through="task_manager.WorkerTeam", to="task_manager.team"
            ),
        ),
    ]
